### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Imma-P** [ErezAmihud/dearmor#15]
Hello, I get this error 

OSError: [WinError 193] %1 is not a valid Win32 application

How can I fix? Thank you

![Immagine](https://github.com/ErezAmihud/dearmor/assets/66201707/530a0952-2520-4bfb-a75e-a5876d3e6baa)

**Comment by ErezAmihud** [comment]
Python is probably not installed correctly, or that the pyc file was not created in windows.

To check if python is installed correctly try using pyarmor to obfuscate python file and then use dearmor. (Note, if you installed python from the microsoft store, remove it and install from python official site)

To check if the pyc is the problem, decompile the pyc into py file using `pycdc` or `decompyle` and then try to run with it.
