### ISSUE TITLE
[Guide Needed] Add Guide for keeping main files

### ISSUE THREAD

**Issue by MikeAndarsons** [ErezAmihud/dearmor#7]
Add Guide for keeping main files after decompilation using python-exe-unpacker  ,i mean  which files are necessary to deobfuscate script

**Comment by ErezAmihud** [comment]
@MikeAndarsons 

I dont have time to do it, but you actually dont need to unpack, only run the obfuscated python exe and inject the dll to it.
Download the git content, go to dearmor/__main__.py and edit line 18 remove sys.executable (and the "," that comes after that)

Then install and run

In the -i option just put your exe instead

**Comment by MikeAndarsons** [comment]
@ErezAmihud 
Thanks for answering,I changed main.py as you said  and installed.
Now i am using command like:
`dearmor -i "App.exe"`
That App is opening but in CMD i got error:
```

Traceback (most recent call last):
  File "C:\Users\WINDOWS10\AppData\Local\Programs\Python\Python37\Scripts\dearmor-script.py", line 11, in <module>
    load_entry_point('dearmor==0.1', 'console_scripts', 'dearmor')()
  File "C:\Users\WINDOWS10\AppData\Local\Programs\Python\Python37\lib\site-packages\dearmor-0.1-py3.7-win-amd64.egg\dearmor\__main__.py", line 35, in main_cli
    main(print_user_messages=True, **parser.parse_args().__dict__)
  File "C:\Users\WINDOWS10\AppData\Local\Programs\Python\Python37\lib\site-packages\dearmor-0.1-py3.7-win-amd64.egg\dearmor\__main__.py", line 22, in main
    inject(child[0].pid, str(Path(__file__).parent.parent / "dearmor-library" / "lib" / "dearmor.dll"))
IndexError: list index out of range
```

**Comment by MikeAndarsons** [comment]
@ErezAmihud Any Solution? or can you suggest other methods to deobfuscate ?

**Comment by ErezAmihud** [comment]
@MikeAndarsons 
Hi, I uploaded the package to the pypi artifactory at https://pypi.org/project/dearmor/0.2/ I think it will solve your problems.

Using -i with the exe should be fine. The traceback you sent looks like it is a problem with the compilation script in setup.py. Install from the pypi.org and it will be fine

**Comment by ShuRaymond** [comment]
Hello, why is there no response after I type dearmor -i xxx.exe

**Comment by ErezAmihud** [comment]
> Hello, why is there no response after I type dearmor -i xxx.exe

I edited to comment above, decompile the exe first to something you can run `python <file>`.
Also install all the dependencies packages
